image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - mkaufman.HTMLHint@0.6.0:TdNYbCmjW8N3yiaPW4/adg==
    - eventyret.bootstrap-4-cdn-snippet@1.6.0:AtNd6GnbCYVpmUkOaFXs3A==
    - kevinglasson.cornflakes-linter@0.4.0:Sgfmpf9YWoF5/BDJu2xn0w==
    - wholroyd.jinja@0.0.8:C3zsj1nZxSJZh/EcV6Hjlg==
    - esbenp.prettier-vscode@5.0.1:RwSu+IlJT2eB3vwdygaJUQ==
    - formulahendry.auto-close-tag@0.5.7:ofk2Iz4wGQdoTFrnRwzI7w==
    - batisteo.vscode-django@0.20.0:gUr2ptf5xx2Pcb6pNcYqgw==
    - mblode.pretty-formatter@0.2.1:zRQLKZopqBmlD8T9DoUpsQ==